# Generated by Django 4.2.30 on 2026-05-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucherrequest_voucher_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valeur du voucher en DZD', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix de vente en DZD', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.RemoveField(
            model_name='voucherrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='voucherrequest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='voucherrequest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='voucherrequest',
            name='value',
        ),
        migrations.AddField(
            model_name='voucherrequest',
            name='price_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='vouchers.voucherprice'),
        ),
    ]
