# Generated by Django 4.2.30 on 2026-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucherprice_remove_voucherrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherprice',
            name='pack_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de vouchers dans ce pack'),
        ),
        migrations.AlterField(
            model_name='voucherprice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix de vente en DZD pour le pack', max_digits=10),
        ),
    ]
