# Generated by Django 4.2.30 on 2026-05-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_voucherprice_pack_quantity_alter_voucherprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('BLANK', 'Vide'), ('ACTIVE', 'Actif'), ('USED', 'Utilisé'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
