# Generated by Django 4.2.30 on 2026-05-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucher_customer_name_voucher_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
