# Generated by Django 4.2.30 on 2026-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_voucher_beneficiary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
