# Generated by Django 4.2.30 on 2026-05-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_voucher_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
