# Generated by Django 4.2.30 on 2026-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_voucher_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='remaining_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
