name: 🚀 Deploy Project
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Check Code
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4